version: '3.4'

networks:
  localnetwork:
    name: localnetwork

services:
  webapp:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 7000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=852789sc
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_HTTPS_PORT=8005
    depends_on:
      - db
    networks:
      - localnetwork
    volumes:
      - ~/.aspnet/https:/https:ro
      - ~/.microsoft/usersecrets:/usersecrets:ro

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - SA_PASSWORD=123qwe
      - ACCEPT_EULA=Y
      # - TCP_PORT=1433
    ports:
      - 1400:1433
    networks:
      - localnetwork


# version: '3.4'
# services:
#  eshopwebmvc:
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#      - ASPNETCORE_URLS=http://+:80
#    ports:
#      - "5106:80"
#    volumes:
#      - ~/.aspnet/https:/root/.aspnet/https:ro
#      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro