#Digital Ocean Acceptable Version 3.3
version: '3.3'

services:
  web:
    container_name: 'saed'
    image: 't4zo/saed:0.0.2'
    build:
      context: .
      dockerfile: heroku.dockerfile
    ports:
      - 5000:5000
      - 5001:5001
    depends_on:
      - postgres
    environment:
      DOCKER: 'True'
      ASPNETCORE_ENVIRONMENT: 'Production'
      ConnectionStrings__DefaultConnection: 'Host=postgres;Database=saeddb;User ID=postgres;Port=5432;Password=582789sc'
      # ConnectionStrings__DefaultConnection: 'Host=db-postgresql-nyc3-59221-do-user-6472039-0.a.db.ondigitalocean.com;Port=25060;Database=defaultdb;User Id=doadmin;Password=i6idekdph02w2meg;SSL Mode=Require;Trust Server Certificate=true'
      ASPNETCORE_HTTPS_PORT: '5001'
      ASPNETCORE_URLS: 'https://+:5001;http://+:5000'
      ASPNETCORE_Kestrel__Certificates__Default__Path: '/https/aspnetapp.pfx'
      ASPNETCORE_Kestrel__Certificates__Default__Password: 'password'
    volumes:
      - ~/.aspnet/https:/https:ro
    networks:
      - saed-network

  postgres:
    container_name: 'postgres'
    image: postgres:10
    environment:
      POSTGRES_DB: 'saeddb'
      POSTGRES_PASSWORD: '582789sc'
    volumes:
      - db_volume:/var/lib/postgresql/data
    networks:
      - saed-network

  nginx:
    image: nginx:1.19-alpine
    container_name: saed-nginx
    restart: unless-stopped
    links:
      - web:web
    ports:
      - 80:5000
      - 443:5001
    volumes:
      - ./:/var/www
      - ./nginx/app.conf:/etc/nginx/nginx.conf
      - ./docker-compose/nginx:/etc/nginx/conf.d/
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    networks:
      - saed-network
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  db_volume:

networks:
  saed-network:
    driver: bridge