name: AWS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, world!

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: github.ref == 'refs/heads/main'

  #   steps:
  #     - name: Configure AWS credentials
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: us-east-1

  #     - name: Create CodeDeploy Deployment
  #       id: deploy
  #       run: |
  #         aws deploy create-deployment \
  #           --application-name saed \
  #           --deployment-group-name saed-development \
  #           --deployment-config-name CodeDeployDefault.AllAtOnce \
  #           --github-location repository=${{ github.repository }},commitId=${{ github.sha }} \
  #           --file-exists-behavior=OVERWRITE \
  #           --auto-rollback-configuration enabled=true,events=DEPLOYMENT_FAILURE
