name: AWS

on: 
  workflow_dispatch:

#   push:
#     branches: 
#       - main

#   pull_request:
#     branches: 
#       - main

env:
  DOCKERHUB_IMAGE_URL: https://hub.docker.com/repository/docker/t4zo/saed
  SAED_URL: https://saed.t4zo.com/health
  AWS_REGION: us-east-1
  APPLICATION_NAME: AppECS-t4zo-saed
  DEPLOYMENT_GROUP_NAME: DgpECS-t4zo-saed
  BUCKET_NAME: saed-application

jobs:
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name saed \
            --deployment-group-name saed-development \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }} \
            --file-exists-behavior=OVERWRITE \
            --auto-rollback-configuration enabled=true,events=DEPLOYMENT_FAILURE
