name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore SAED.Web
        run: dotnet restore ./src/SAED.Web/SAED.Web.csproj

      - name: Build SAED.Web
        run: dotnet build -c Release --no-restore ./src/SAED.Web/SAED.Web.csproj

      - name: Restore SAED.Api
        run: dotnet restore ./src/SAED.Api/SAED.Api.csproj

      - name: Build SAED.Api
        run: dotnet build -c Release --no-restore ./src/SAED.Api/SAED.Api.csproj