name: Digital Ocean

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, world!

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Deploy to droplet using SSH
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.HOST }}
  #         username: ${{ secrets.USERNAME }}
  #         password: ${{ secrets.PASSWORD }}
  #         # key: ${{ secrets.PRIVATE_KEY }}
  #         debug: true
  #         script: |
  #           logname
  #           sudo systemctl stop saed
  #           cd ${{ secrets.DOCROOT }}
  #           git pull
  #           cd ${{ secrets.DOCROOT }}/SAED.Web/
  #           dotnet build -c Release
  #           dotnet publish -c Release --no-build
  #           cd ${{ secrets.DOCROOT }}/
  #           dotnet-ef database update -s SAED.Web -p SAED.Persistence
  #           sudo systemctl start saed

  #     # - name: Invoke deployment hook
  #     #   uses: distributhor/workflow-webhook@v1.0.5
  #     #   env:
  #     #     webhook_url: ${{ secrets.WEBHOOK_URL }}
  #     #     webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
  #     #     webhook_auth: ${{ secrets.WEBHOOK_AUTH }}
