name: Docker

on: workflow_dispatch
# on:
#   push:
#     branches: 
#       - main

#   pull_request:
#     branches: 
#       - main

jobs:
  docker:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    environment:
      name: Development

    env:
      DOCKERHUB_USER_IMAGE_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB__IMAGE_TAG }}
      GITHUB_USER_IMAGE_TAG: ${{ github.repository_owner }}/${{ secrets.DOCKERHUB__IMAGE_TAG }}

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: docker build -f Dockerfile -t ${{ env.GITHUB_USER_IMAGE_TAG }} .

      - name: Login DockerHub
        run: echo "${{secrets.DOCKERHUB_ACCESS_TOKEN}}" | docker login -u ${{ github.repository_owner }} --password-stdin

      - name: Push
        run: docker push ${{ env.GITHUB_USER_IMAGE_TAG }}
