name: Docker

on:
  workflow_run:
    workflows: ["build"]
    branches: [main]
    types:
      - completed
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    environment:
      name: Development

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: docker build -f Dockerfile -t ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.DOCKERHUB__IMAGE_TAG}} .

      - name: Login DockerHub
        run: echo "${{secrets.DOCKERHUB_ACCESS_TOKEN}}" | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin

      - name: Push
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.DOCKERHUB__IMAGE_TAG}}

# buildx failed with: ERROR: failed to solve: failed to read dockerfile: open /tmp/buildkit-mount3174352312/Dockerfile: no such file or directory
  # push:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v2

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2

  #     - name: Login to DockerHub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
  #         ecr: auto
  #         logout: true

  #     - name: Build and push
  #       uses: docker/build-push-action@v3
  #       with:
  #         context: .
  #         push: ${{ github.ref == 'refs/heads/main' }}
  #         tags: ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.DOCKERHUB__IMAGE_TAG}}
