name: SAED Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
      - name: Build with dotnet
        run: dotnet build --configuration Release --no-restore ./src/Web/SAED.Web.csproj
      - name: Test with dotnet
        run: dotnet test --configuration Release ./src/Api/SAED.Api.csproj
