name: Amazon EC2

on:
  workflow_run:
    workflows: ["docker"]
    branches: [main]
    types:
      - completed
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Run a one-line script
        run: echo Hello, world!

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Deploy to EC2 using SSH
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.HOST }}
  #         username: ${{ secrets.USERNAME }}
  #         password: ${{ secrets.PASSWORD }}
  #         # key: ${{ secrets.PRIVATE_KEY }}
  #         debug: true
  #         script: |
  #           logname
  #           sudo docker container stop saed
  #           sudo docker pull ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.DOCKERHUB__IMAGE_TAG}}
  #           sudo docker container prune -f
  #           sudo docker container ${{ secrets.DOCKER_RUN }}
